version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: skyeye-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: skyeye123
      MYSQL_DATABASE: skyeye
      MYSQL_USER: skyeye
      MYSQL_PASSWORD: skyeye123
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - skyeye-network

  redis:
    image: redis:6.2
    container_name: skyeye-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - skyeye-network

networks:
  skyeye-network:
    driver: bridge 