server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: skyeye-server
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/skyeye?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: skyeye123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
      
  # 解决Springfox与Spring Boot 2.7.x的兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 文件编码配置
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# JWT配置
jwt:
  secret: skyeye_secret_key_must_have_at_least_32_characters
  expiration: 86400000  # 24小时

# 日志配置
logging:
  level:
    root: INFO
    com.skyeye: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  config: classpath:logback-spring.xml
  charset: UTF-8
  file:
    name: logs/skyeye.log

# 文件上传配置
file:
  upload-dir: ./uploads 